-- Paises
INSERT INTO paises (pais, nombre) VALUES (1, 'Paraguay');
INSERT INTO paises (pais, nombre) VALUES (2, 'Argentina');
INSERT INTO paises (pais, nombre) VALUES (3, 'Concepción');
INSERT INTO paises (pais, nombre) VALUES (4, 'Concepción');
-- Departamentos
-- Departamentos del Paraguay
INSERT INTO departamentos (departamento, pais, nombre) VALUES (1, 1, 'Concepción');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (2, 1, 'San Pedro');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (3, 1, 'Cordillera');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (4, 1, 'Guairá');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (5, 1, 'Caaguazú');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (6, 1, 'Caazapá');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (7, 1, 'Itapúa');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (8, 1, 'Misiones');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (9, 1, 'Paraguarí');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (10, 1, 'Alto Paraná');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (11, 1, 'Central');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (12, 1, 'Ñeembucú');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (13, 1, 'Amambay');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (14, 1, 'Canindeyú');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (15, 1, 'Presidente Hayes');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (16, 1, 'Alto Paraguay');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (17, 1, 'Boquerón');
-- Provincias de la Argentina
INSERT INTO departamentos (departamento, pais, nombre) VALUES (18, 2, 'Buenos Aires');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (19, 2, 'Catamarca');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (20, 2, 'Chaco');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (21, 2, 'Chubut');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (22, 2, 'Córdoba');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (23, 2, 'Corrientes');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (24, 2, 'Entre Ríos');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (25, 2, 'Formosa');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (26, 2, 'Jujuy');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (27, 2, 'La Pampa');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (28, 2, 'La Rioja');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (29, 2, 'Mendoza');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (30, 2, 'Misiones');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (31, 2, 'Neuquén');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (32, 2, 'Río Negro');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (33, 2, 'Salta');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (34, 2, 'San Juan');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (35, 2, 'San Luis');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (36, 2, 'Santa Cruz');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (37, 2, 'Santa Fe');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (38, 2, 'Santiago del Estero');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (39, 2, 'Tierra del Fuego');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (40, 2, 'Tucumán');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (41, 2, 'Ciudad Autónoma de Buenos Aires');
-- Estados del Brasil
INSERT INTO departamentos (departamento, pais, nombre) VALUES (42, 3, 'Acre');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (43, 3, 'Alagoas');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (44, 3, 'Amapá');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (45, 3, 'Amazonas');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (46, 3, 'Bahía');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (47, 3, 'Ceará');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (48, 3, 'Distrito Federal');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (49, 3, 'Espírito Santo');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (50, 3, 'Goiás');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (51, 3, 'Maranhão');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (52, 3, 'Mato Grosso');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (53, 3, 'Mato Grosso do Sul');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (54, 3, 'Minas Gerais');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (55, 3, 'Pará');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (56, 3, 'Paraíba');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (57, 3, 'Paraná');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (58, 3, 'Pernambuco');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (59, 3, 'Piauí');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (60, 3, 'Río de Janeiro');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (61, 3, 'Río Grande del Norte');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (62, 3, 'Río Grande del Sur');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (63, 3, 'Rondônia');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (64, 3, 'Roraima');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (65, 3, 'Santa Catarina');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (66, 3, 'São Paulo');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (67, 3, 'Sergipe');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (68, 3, 'Tocantins');
-- Departamentos del Uruguay
INSERT INTO departamentos (departamento, pais, nombre) VALUES (69, 4, 'Artigas');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (70, 4, 'Canelones');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (71, 4, 'Cerro Largo');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (72, 4, 'Colonia');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (73, 4, 'Durazno');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (74, 4, 'Flores');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (75, 4, 'Florida');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (76, 4, 'Lavalleja');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (77, 4, 'Maldonado');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (78, 4, 'Montevideo');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (79, 4, 'Paysandú');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (80, 4, 'Río Negro');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (81, 4, 'Rivera');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (82, 4, 'Rocha');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (83, 4, 'Salto');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (84, 4, 'San José');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (85, 4, 'Soriano');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (86, 4, 'Tacuarembó');
INSERT INTO departamentos (departamento, pais, nombre) VALUES (87, 4, 'Treinta y Tres');